name: PR-ism All-in-One

on:
  pull_request:
    types: [opened, review_requested, review_request_removed, labeled, unlabeled]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: read

env:
  WEBHOOK_URL: "https://stats.pr-ism.site"
  PRISM_API_KEY: ${{ secrets.PRISM_API_KEY }}

jobs:
  collect-pr-opened:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Handle opened event
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_DATA=$(gh api graphql -f query='
            query($owner: String!, $repo: String!, $number: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $number) {
                  number
                  title
                  url
                  additions
                  deletions
                  changedFiles
                  createdAt
                  author { login }
                  commits(first: 100) {
                    totalCount
                    nodes {
                      commit {
                        oid
                        committedDate
                      }
                    }
                  }
                }
              }
            }
          ' -f owner='${{ github.repository_owner }}' \
            -f repo='${{ github.event.repository.name }}' \
            -F number=${{ github.event.pull_request.number }})

          FILES_DATA=$(gh api \
            "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
            --jq '[.[] | {filename, status, additions, deletions}]')

          PAYLOAD=$(jq -n \
            --argjson prData "$PR_DATA" \
            --argjson files "$FILES_DATA" \
            --argjson isDraft "${{ github.event.pull_request.draft }}" \
            '{
              isDraft: $isDraft,
              pullRequest: $prData.data.repository.pullRequest,
              files: $files
            }')

          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.PRISM_API_KEY }}" \
              -d "$PAYLOAD" "$WEBHOOK_URL/webhook/pull-request/opened" --fail --silent --show-error
          fi

  collect-reviewer:
    if: github.event.action == 'review_requested' || github.event.action == 'review_request_removed'
    runs-on: ubuntu-latest
    steps:
      - name: Handle review_requested event
        if: github.event.action == 'review_requested'
        run: |
          PAYLOAD=$(jq -n \
            --argjson pullRequestNumber "${{ github.event.pull_request.number }}" \
            --arg login "${{ github.event.requested_reviewer.login }}" \
            --argjson id "${{ github.event.requested_reviewer.id }}" \
            --arg requestedAt "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            '{
              pullRequestNumber: $pullRequestNumber,
              reviewer: {
                login: $login,
                id: $id
              },
              requestedAt: $requestedAt
            }')

          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.PRISM_API_KEY }}" \
              -d "$PAYLOAD" "$WEBHOOK_URL/webhook/reviewer/added" --fail --silent --show-error
          fi

      - name: Handle review_request_removed event
        if: github.event.action == 'review_request_removed'
        run: |
          PAYLOAD=$(jq -n \
            --argjson pullRequestNumber "${{ github.event.pull_request.number }}" \
            --arg login "${{ github.event.requested_reviewer.login }}" \
            --argjson id "${{ github.event.requested_reviewer.id }}" \
            --arg removedAt "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            '{
              pullRequestNumber: $pullRequestNumber,
              reviewer: {
                login: $login,
                id: $id
              },
              removedAt: $removedAt
            }')

          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.PRISM_API_KEY }}" \
              -d "$PAYLOAD" "$WEBHOOK_URL/webhook/reviewer/removed" --fail --silent --show-error
          fi

  collect-pr-label:
    if: github.event.action == 'labeled' || github.event.action == 'unlabeled'
    runs-on: ubuntu-latest
    steps:
      - name: Handle labeled event
        if: github.event.action == 'labeled'
        run: |
          PAYLOAD=$(jq -n \
            --argjson pullRequestNumber "${{ github.event.pull_request.number }}" \
            --arg labelName "${{ github.event.label.name }}" \
            --arg labeledAt "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            '{
              pullRequestNumber: $pullRequestNumber,
              label: {
                name: $labelName
              },
              labeledAt: $labeledAt
            }')

          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.PRISM_API_KEY }}" \
              -d "$PAYLOAD" "$WEBHOOK_URL/webhook/pull-request/label/added" --fail --silent --show-error
          fi

      - name: Handle unlabeled event
        if: github.event.action == 'unlabeled'
        run: |
          PAYLOAD=$(jq -n \
            --argjson pullRequestNumber "${{ github.event.pull_request.number }}" \
            --arg labelName "${{ github.event.label.name }}" \
            --arg unlabeledAt "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            '{
              pullRequestNumber: $pullRequestNumber,
              label: {
                name: $labelName
              },
              unlabeledAt: $unlabeledAt
            }')

          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.PRISM_API_KEY }}" \
              -d "$PAYLOAD" "$WEBHOOK_URL/webhook/pull-request/label/removed" --fail --silent --show-error
          fi

  collect-review-submitted:
    if: github.event_name == 'pull_request_review' && github.event.action == 'submitted'
    runs-on: ubuntu-latest
    steps:
      - name: Handle review submitted event
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT_COUNT=$(gh api \
            "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews/${{ github.event.review.id }}/comments" \
            --jq 'length')

          PAYLOAD=$(jq -n \
            --argjson githubPullRequestId "${{ github.event.pull_request.id }}" \
            --argjson pullRequestNumber "${{ github.event.pull_request.number }}" \
            --argjson githubReviewId "${{ github.event.review.id }}" \
            --arg reviewerLogin "${{ github.event.review.user.login }}" \
            --argjson reviewerId "${{ github.event.review.user.id }}" \
            --arg state "${{ github.event.review.state }}" \
            --arg commitSha "${{ github.event.review.commit_id }}" \
            --arg body "${{ github.event.review.body }}" \
            --argjson commentCount "$COMMENT_COUNT" \
            --arg submittedAt "${{ github.event.review.submitted_at }}" \
            '{
              githubPullRequestId: $githubPullRequestId,
              pullRequestNumber: $pullRequestNumber,
              githubReviewId: $githubReviewId,
              reviewer: {
                login: $reviewerLogin,
                id: $reviewerId
              },
              state: $state,
              commitSha: $commitSha,
              body: $body,
              commentCount: $commentCount,
              submittedAt: $submittedAt
            }')

          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.PRISM_API_KEY }}" \
              -d "$PAYLOAD" "$WEBHOOK_URL/webhook/review/submitted" --fail --silent --show-error
          fi

  collect-review-comment:
    if: github.event_name == 'pull_request_review_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Handle review comment created event
        if: github.event.action == 'created'
        run: |
          PAYLOAD=$(jq -n \
            --argjson githubCommentId "${{ github.event.comment.id }}" \
            --argjson githubReviewId "${{ github.event.comment.pull_request_review_id }}" \
            --arg body "${{ github.event.comment.body }}" \
            --arg path "${{ github.event.comment.path }}" \
            --argjson line "${{ github.event.comment.line || 0 }}" \
            --argjson startLine "${{ github.event.comment.start_line || 'null' }}" \
            --arg side "${{ github.event.comment.side }}" \
            --arg commitSha "${{ github.event.comment.commit_id }}" \
            --argjson inReplyToId "${{ github.event.comment.in_reply_to_id || 'null' }}" \
            --arg authorLogin "${{ github.event.comment.user.login }}" \
            --argjson authorId "${{ github.event.comment.user.id }}" \
            --arg createdAt "${{ github.event.comment.created_at }}" \
            --arg updatedAt "${{ github.event.comment.updated_at }}" \
            '{
              githubCommentId: $githubCommentId,
              githubReviewId: $githubReviewId,
              body: $body,
              path: $path,
              line: $line,
              startLine: $startLine,
              side: $side,
              commitSha: $commitSha,
              inReplyToId: $inReplyToId,
              author: {
                login: $authorLogin,
                id: $authorId
              },
              createdAt: $createdAt,
              updatedAt: $updatedAt
            }')

          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.PRISM_API_KEY }}" \
              -d "$PAYLOAD" "$WEBHOOK_URL/webhook/review-comment/created" --fail --silent --show-error
          fi

      - name: Handle review comment edited event
        if: github.event.action == 'edited'
        run: |
          PAYLOAD=$(jq -n \
            --argjson githubCommentId "${{ github.event.comment.id }}" \
            --arg body "${{ github.event.comment.body }}" \
            --arg updatedAt "${{ github.event.comment.updated_at }}" \
            '{
              githubCommentId: $githubCommentId,
              body: $body,
              updatedAt: $updatedAt
            }')

          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.PRISM_API_KEY }}" \
              -d "$PAYLOAD" "$WEBHOOK_URL/webhook/review-comment/edited" --fail --silent --show-error
          fi

  collect-review-request-notification:
    if: github.event.action == 'review_requested'
    runs-on: ubuntu-latest
    env:
      WEBHOOK_URL: "https://slack.pr-ism.site"
    steps:
      - name: Handle review requested event
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"

          PENDING_RAW=$(gh api "repos/$OWNER/$REPO/pulls/$PR_NUMBER/requested_reviewers" || echo '{"users":[],"teams":[]}')
          REVIEWED_RAW=$(gh api --paginate "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews" || echo '[]')

          PENDING_USERS=$(echo "$PENDING_RAW" | jq -r --arg author "$AUTHOR" '[.users[].login? | select(. != $author)]')
          REVIEWED_USERS=$(echo "$REVIEWED_RAW" | jq -r --arg author "$AUTHOR" '[.[].user.login? | select(. != $author)] | sort | unique')

          PAYLOAD=$(jq -n \
            --arg repo "$REPO" \
            --arg prId "PR-$PR_NUMBER" \
            --argjson prNumber "$PR_NUMBER" \
            --arg prTitle "${{ github.event.pull_request.title }}" \
            --arg prUrl "${{ github.event.pull_request.html_url }}" \
            --arg author "$AUTHOR" \
            --argjson pending "$PENDING_USERS" \
            --argjson reviewed "$REVIEWED_USERS" \
            '{
              repositoryName: $repo,
              pullRequestId: $prId,
              pullRequestNumber: $prNumber,
              pullRequestTitle: $prTitle,
              pullRequestUrl: $prUrl,
              authorGithubId: $author,
              pendingReviewers: $pending,
              reviewedReviewers: $reviewed
            }')

          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.PRISM_API_KEY }}" \
              -d "$PAYLOAD" "$WEBHOOK_URL/events/review-request" --fail --silent --show-error
          fi
