name: PR-ism Review Requested Metrics
on:
  pull_request:
    types: [review_requested]

jobs:
  collect-review-requested:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Review Requested Metadata
        uses: pr-ism/action-collect@v1
        with:
          api-key: ${{ secrets.PRISM_API_KEY }}
          event-type: review_requested
          pr-url: ${{ github.event.pull_request.html_url }}
          author: ${{ github.event.pull_request.user.login }}
          reviewers: ${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}
          requested-at: ${{ github.event.action }}
